// Regenerated by `npm run types` in worker/. Secrets live in .dev.vars / wrangler secret.
interface Env {
  SUPABASE_URL: string;
  SUPABASE_ANON_KEY: string;
  SUPABASE_SERVICE_ROLE_KEY: string;
  GOOGLE_MAPS_SERVER_KEY: string;
}

declare namespace Cloudflare {
  interface Env {
    SUPABASE_URL: string;
    SUPABASE_ANON_KEY: string;
    SUPABASE_SERVICE_ROLE_KEY: string;
    GOOGLE_MAPS_SERVER_KEY: string;
  }
}
